// Phone / WhatsApp country codes — African countries first, then international
export const PHONE_CODES = [
  { code: '+228', label: '🇹🇬 Togo (+228)' },
  { code: '+234', label: '🇳🇬 Nigeria (+234)' },
  { code: '+233', label: '🇬🇭 Ghana (+233)' },
  { code: '+229', label: '🇧🇯 Bénin (+229)' },
  { code: '+225', label: '🇨🇮 Côte d\'Ivoire (+225)' },
  { code: '+221', label: '🇸🇳 Sénégal (+221)' },
  { code: '+223', label: '🇲🇱 Mali (+223)' },
  { code: '+226', label: '🇧🇫 Burkina Faso (+226)' },
  { code: '+227', label: '🇳🇪 Niger (+227)' },
  { code: '+237', label: '🇨🇲 Cameroun (+237)' },
  { code: '+241', label: '🇬🇦 Gabon (+241)' },
  { code: '+242', label: '🇨🇬 Congo (+242)' },
  { code: '+243', label: '🇨🇩 RD Congo (+243)' },
  { code: '+212', label: '🇲🇦 Maroc (+212)' },
  { code: '+213', label: '🇩🇿 Algérie (+213)' },
  { code: '+216', label: '🇹🇳 Tunisie (+216)' },
  { code: '+20',  label: '🇪🇬 Égypte (+20)' },
  { code: '+27',  label: '🇿🇦 Afrique du Sud (+27)' },
  { code: '+33',  label: '🇫🇷 France (+33)' },
  { code: '+32',  label: '🇧🇪 Belgique (+32)' },
  { code: '+41',  label: '🇨🇭 Suisse (+41)' },
  { code: '+1',   label: '🇺🇸 USA / Canada (+1)' },
  { code: '+44',  label: '🇬🇧 Royaume-Uni (+44)' },
  { code: '+49',  label: '🇩🇪 Allemagne (+49)' },
  { code: '+34',  label: '🇪🇸 Espagne (+34)' },
  { code: '+39',  label: '🇮🇹 Italie (+39)' },
]

export const NATIONALITIES = [
  'Togolaise', 'Nigériane', 'Ghanéenne', 'Béninoise', "Ivoirienne",
  'Sénégalaise', 'Malienne', 'Burkinabé', 'Nigérienne', 'Camerounaise',
  'Gabonaise', 'Congolaise', 'Marocaine', 'Algérienne', 'Tunisienne',
  'Égyptienne', 'Sud-Africaine', 'Française', 'Belge', 'Suisse',
  'Américaine', 'Britannique', 'Allemande', 'Espagnole', 'Italienne', 'Autre',
]
